### ISSUE TITLE
Unexpected Token . 

### ISSUE THREAD

**Issue by elwood241** [Altpapier/hypixel-discord-guild-bridge#10]
While trying to start the bridge ( typing "node . " in console) it shows me the error:

/root/hypixel-discord-guild-bridge/index.js:29
                ?.send(`${config.minecraft.ingameName + ' has' || 'I have'} been disconnected from Hypixel. Trying to reconnect...`);
                 ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by Altpapier** [comment]
what nodejs version are you using? (`node -v`)

**Comment by elwood241** [comment]
yea.. that was the issue
version was <16 not >=16
now its 16.18.0
thank you
